openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths: {}
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - dateOfBirth
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
        dateOfBirth:
          type: string
          format: date
        lastFedAt:
          type: string
          format: date-time
        earTagUuid:
          type: string
          format: uuid
        imageUrl:
          type: string
          format: uri
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Pet"
